// declare calendar events here
// Y0000 is generic year, containing annually recurring events
var CALENDAR_EVENTS = {
    Y0000: [
        // birthdays
        [22, 9, "Aanya Sharma's Birthday"],
        [31, 7, "Atharva Sharma's Birthday"],
        [7, 8, "Bhavya Choudhary's Birthday"],
        [5, 0, "Bhumika Rathi's Birthday"],
        [22, 9, "Chitransh Agrawal's Birthday"],
        [4, 11, "Devanshi Sharma's Birthday"],
        [17, 7, "Dipanshu Choudhary's Birthday"],
        [25, 3, "Gourav Saini's Birthday"],
        [6, 8, "Harsh's Birthday"],
        [20, 11, "Harshita's Birthday"],
        [16, 9, "Ishika's Birthday"],
        [25, 9, "Jaanvi's Birthday"],
        [27, 11, "Jigyasa Sharma's Birthday"],
        [10, 3, "Kartikay Sharma's Birthday"],
        [5, 0, "Keshav Vyas's Birthday"],
        [2, 8, "Krishna Meena's Birthday"],
        [19, 9, "Krishna Saini's Birthday"],
        [21, 11, "Kunal Jangid's Birthday"],
        [5, 6, "Madhavi Kumawat's Birthday"],
        [27, 4, "Niharika Jangid's Birthday"],
        [20, 3, "Nitin Singh Gehlot's Birthday"],
        [22, 10, "Pari Yadav's Birthday"],
        [1, 8, "Pradhuman Singh's Birthday"],
        [23, 11, "Pranjal Singh Meena's Birthday"],
        [16, 4, "Reyansh Jangir's Birthday"],
        [17, 0, "Rishabh Ola's Birthday"],
        [7, 7, "Ritu Rarh's Birthday"],
        [15, 10, "Sameer's Birthday"],
        [19, 4, "Shivam Sharma's Birthday"],
        [18, 6, "Suhana Budania's Birthday"],
        [10, 11, "Suman's Birthday"],
        [11, 8, "Supriya Yadav's Birthday"],
        [18, 8, "Vihan Chhabarwal's Birthday"],
        [13, 10, "Vihaan Choudhary's Birthday"],
        [24, 11, "Yashasvi Kumawat's Birthday"],
        [16, 11, "Sourabh Sir's Birthday"],
    ],
};
